spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    initialize: false
    driver-class-name: com.mysql.jdbc.Driver
    database: orderdb
    host: 127.0.0.1
    port: 3306
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  jade4j:
    caching: false
    prefix: file:E:\orderfood\views\templates\
  resources:
    static-locations: file:E:\orderfood\views\static\

---
spring:
  profiles: test
  datasource:
    initialize: false
    driver-class-name: com.mysql.jdbc.Driver
    database: orderdb
    host: 127.0.0.1
    port: 3306
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  jade4j:
    caching: false
    prefix: file:E:\orderfood\views\templates\
  resources:
    static-locations: file:E:\orderfood\views\static\
---
mybatis:
    type-aliases-package: com.platform.api.model.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
      cache-enabled: false
mapper:
    mappers:
        - com.orderfood.mapper.CommonMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
    com.demo.mapper: trace
server:
  port: 8080
##jwt配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800
